'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



<Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
 Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")>  _
Partial Friend NotInheritable Class StartUp
    Inherits Global.System.Configuration.ApplicationSettingsBase
    
    Private Shared defaultInstance As StartUp = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New StartUp()),StartUp)
    
    Public Shared ReadOnly Property [Default]() As StartUp
        Get
            Return defaultInstance
        End Get
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
    Public Property Style() As Integer
        Get
            Return CType(Me("Style"),Integer)
        End Get
        Set
            Me("Style") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
    Public Property Robot_Program() As Integer
        Get
            Return CType(Me("Robot_Program"),Integer)
        End Get
        Set
            Me("Robot_Program") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property Ready() As Boolean
        Get
            Return CType(Me("Ready"),Boolean)
        End Get
        Set
            Me("Ready") = value
        End Set
    End Property
End Class
